### ISSUE TITLE
Installation Error idk iam idiot..

### ISSUE THREAD

**Issue by ghost** [nomadics9/nixcfg#1]
Hey,

I totally messed up while following your installation guide. I used GNOME as you said and ran the install.sh script with root privileges, but then I hit a snag. Here’s what happened:

[cipisek@nixos:~]$ sudo git clone https://github.com/nomadics9/nixcfg.git
Cloning into 'nixcfg'...
(remote output)
I navigated into the directory and ran the script:

[cipisek@nixos:~/nixcfg]$ sudo bash install.sh
The output looked good at first, like:

Enter the new username: cipisek
Enter the new hostname: cipisek
Creating Host configuration for cipisek... 
(Creating User configuration for cipisek... and so on...)
But then I got this error:

cp: cannot stat './home/nomad/home.nix': No such file or directory
Home configuration for cipisek created successfully!
After that, it continued with more errors:

error: getting status of '/nix/store/c11gslb8cw6yc76ymni5gdjnjfyycp4f-source/hosts/cipisek': No such file or directory
So yeah, it seems like I really screwed something up here. Any idea what I did wrong? Thanks for your help!

**Comment by nomadics9** [comment]
Hey!
My bad I have changed the home dir structure when i added vps host. So it broke the installer trying to copy  home/nomad/home.nix when it should copy from the new path. I will push the fix in a bit. I will keep the issue open to assist you with the installation if you would like that.

**Comment by ghost** [comment]
Hi! Just to confirm—will you be updating the repo and let me know here, or did you mean something else by offering to assist? Thanks!:DD

**Comment by nomadics9** [comment]
yes! I just pushed the changes, I meant I will keep this issue open till u successfully install! let me know how it goes!

**Comment by ghost** [comment]
I encountered the following error while trying to install the system:

Traceback (most recent call last):
  File "/nix/store/bv0j9qw4xc697yxcg8l1ah2gk1j63qcs-systemd-boot/bin/systemd-boot", line 435, in <module>
    main()
  ...
subprocess.CalledProcessError: Command '['/nix/store/pd20hrbbpq39dv9z91p6fkf70pml5bnc-check-mountpoints']' returned non-zero exit status 1.
Failed to install bootloader
warning: error(s) occurred while switching to the new configuration

To fix it, I ran the following command like you said:

sed -i 's|boot.loader.efi.efiSysMountPoint = "/boot/efi";|boot.loader.efi.efiSysMountPoint = "/boot";|' ./hosts/cipisek/configuration.nix

Then, I restarted the installation process with sudo bash install.sh, but I’m not sure if it completed successfully.
During the installation, I received a warning about my Git tree being dirty:


 Using Nomadics dotfiles 
 Configuration has been updated with your preferences 
warning: Git tree '/home/cipisek/nixcfg' is dirty
building the system configuration...
warning: Git tree '/home/cipisek/nixcfg' is dirty
updating systemd-boot from 255.9 to 256.6
Copied "/nix/store/xg6f0c5pchmc2jq84s4np19j1rnn90mn-systemd-256.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/xg6f0c5pchmc2jq84s4np19j1rnn90mn-systemd-256.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
 Reboot after completion your initial password is 4321

**Comment by nomadics9** [comment]
warning: Git tree '/home/cipisek/nixcfg' is dirty
 
 is completly fine. it just means there are some files added. which are the new user and host. if there is no any other errors and it completed. just reboot and it should be installed.

**Comment by ghost** [comment]
Nice i installed it!!! Thx so much:DDD

**Comment by nomadics9** [comment]
Glad I could help 😃
