### ISSUE TITLE
[ Error writing (Some config): Read-only file system ]

### ISSUE THREAD

**Issue by ghost** [nomadics9/nixcfg#2]
Hello, I'm having an issue:
When I try to modify the configuration in hyprland.conf under the Hyprland config, it says: [ Error writing hyprland.conf: Read-only file system ]. I also tried editing the configuration in the regular NixOS config, but it still says it’s read-only. I’m not sure what to do, and I really don’t want this to keep happening.

Any advice would be greatly appreciated.

**Comment by SiPiskej** [comment]
his might be my problem, but I can’t seem to resolve it without addressing the first issue. Here’s the output from rfkill list:

❯ rfkill list       
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: yes
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: yes
	Hard blocked: no
3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no

My Bluetooth is always soft blocked after startup, and I want to ensure everything is working and configured to my preferences. Any advice on how to resolve this would be greatly appreciated!
